### ISSUE TITLE
Framework uses private API, makes no attempt to hide it

### ISSUE THREAD

**Issue by LeoNatan** [molon/MLNavigationBarTransition#1]
For instance,

```
Class cls = NSClassFromString(@"_UINavigationParallaxTransition");
```

This puts the users of your framework in risk with Apple. At least make the smallest effort to hide strings such as `_UINavigationParallaxTransition`.

**Comment by molon** [comment]
@LeoNatan 
https://github.com/molon/MLNavigationBarTransition/commit/c1f7deb0923909a1a870487e2f81b3872911d807
Thanks for your advise, my friend~
:)

**Comment by LeoNatan** [comment]
Cheers!
Cool project!
