### ISSUE TITLE
Framework uses private API, makes no attempt to hide it

### ISSUE THREAD

**Issue by farshadmb** [molon/MLNavigationBarTransition#2]
Non-public API usage:
The app references non-public selectors in App: _currentCustomBackground, _startCustomTransition:

Make hide them @molon

**Comment by molon** [comment]
thanks for tips! :)
https://github.com/molon/MLNavigationBarTransition/commit/cc0731261dd2077009558646519a96bb882b7410

**Comment by farshadmb** [comment]
you 're welcome

**Comment by molon** [comment]
Sorry about the issue.
I hide api you said, but add new un-public api.
Now everything is ok, I have test for appstore just now.
https://github.com/molon/MLNavigationBarTransition/releases/tag/0.0.6

**Comment by farshadmb** [comment]
@molon I haven't any issue after hiding those API. Is un-public API problem remaining?

**Comment by molon** [comment]
@farshadmb No un-public API problem remainning now~

**Comment by farshadmb** [comment]
@molon thanks dude
