### ISSUE TITLE
Crash in iOS 11 beta2

### ISSUE THREAD

**Issue by farshidrasol** [molon/MLNavigationBarTransition#3]
crash in push time in the this method : 
- (UIView*)ml_backgroundView;
because change some variable in UINavigationbar in iOS 11

**Comment by molon** [comment]
https://github.com/ceekay1991/iOS11RuntimeHeaders/blob/master/Frameworks/UIKit.framework/UINavigationBar.h#L53 
the variable is still existed.
Do you has triggerred the `NSAssert` https://github.com/molon/MLNavigationBarTransition/blob/master/Classes/UINavigationBar%2BMLNavigationBarTransition.m#L354

Sorry about this , I have installed Xcode9-beta4.xip four times, but always failed, so I cant debug this.

**Comment by devcxm** [comment]
以下是`UINavigationBar`在iOS 11的所有属性
```
ml_backIndicatorView,
ml_backButtonLabel,
ml_backgroundShadowView,
ml_backgroundView,
ml_currentBackgroundImage,
hash,
superclass,
description,
debugDescription,
_backIndicatorLeftMargin,
_barTranslucence,
_overrideBackgroundExtension,
_deferShadowToSearchBar,
_animationIds,
_startedAnimationTracking,
_stack,
_isContainedInPopover,
_heightIncludingBackground,
refreshControlHost,
_wantsLargeTitleDisplayed,
backgroundEffects,
requestedContentSize,
currentContentSize,
_userContentGuide,
state,
locked,
currentBackButton,
currentLeftView,
currentRightView,
isMinibar,
forceFullHeightInLandscape,
_useInlineBackgroundHeightWhenLarge,
_backgroundOpacity,
_titleOpacity,
alwaysUseDefaultMetrics,
_hidesShadow,
_wantsLetterpressContent,
_backgroundView,
_shadowAlpha,
_disableBlurTinting,
_backdropViewLayerGroupName,
_requestedMaxBackButtonWidth,
_accessibilityButtonBackgroundTintColor,
barStyle,
delegate,
translucent,
topItem,
backItem,
items,
prefersLargeTitles,
tintColor,
barTintColor,
shadowImage,
titleTextAttributes,
largeTitleTextAttributes,
backIndicatorImage,
backIndicatorTransitionMaskImage,
hash,
superclass,
description,
debugDescription,
barPosition
```

iOS11里面已经没有了`currentBackgroundImage`和`backIndicatorView`属性（加上`_backgroundView`共三个属性造成crash）。另外`Ivar *ivars = class_copyIvarList(cls, &ivarCount)`貌似获取不到类的全部的属性（这就是造成farshidrasol crash的原因），改用`objc_property_t *properties  =class_copyPropertyList(cls, &ivarCount)`可以获取到包含`_backgroundView `的属性列表。

这几个问题比较严重，使用了该库的app上架到app store后升级iOS11必造成crash，希望你能够下载xcode9去解决下这个问题。另外个人建议只在DEBUG宏下启用`NSAssert `，因为线上用户打开app直接crash比app UI显示有问题更难接受。

**Comment by molon** [comment]
@devcxm 
非常感谢帮忙查错。
`Xcode9 beta4` 刚出来的那两三天内下载大多都是解压不了，说文件损坏，很多人遇到这状况。
今天我又试了下已经可以解压使用了，一会着手解决此问题。

另外就这个问题我想解释下给后来的人，这个库因使用了大量 `Unpublic API`，编写的时候就已经考虑到了以后可能API会变化的问题。
所以因为 `iOS11` 改名所造成的`crash`都是留下的`NSAssert`触发的，而`NSAssert`默认就是`debug`宏下才会触发，除非有人在项目配置里刻意去改成 `release`模式下也会响应`NSAssert`。总的来说一般不会使得使用此库的线上应用发生`crash`，可以参考下图修改配置运行模拟效果。
![image](https://user-images.githubusercontent.com/3739161/28910253-9847656e-785e-11e7-9f57-8d1eb4858235.png)

**Comment by devcxm** [comment]
搜噶，是我对`NSAssert `理解有误。因为我对`UINavigationBar`的理解没有你透彻，所以还是麻烦作者修改一下源码。另外`KMNavigationBarTransition `在iOS11也有问题 [(issues69)](https://github.com/MoZhouqi/KMNavigationBarTransition/issues/69)，`UINavigationBar`这个东西真难搞。

**Comment by molon** [comment]
@farshidrasol @devcxm 
fixed it: https://github.com/molon/MLNavigationBarTransition/compare/0.0.6...6b54e9b

Because changed the code more, I will delay the release. 
Can you help me test please? 
:)

**Comment by farshidrasol** [comment]
Thank you very much for fixing this problem   👍🏼.
I did the tests and succeeded.
